name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main  # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies and Build
        run: |
            cd QPod
            npm install
            npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: # 👇 Specify build output path
          path: QPod/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
